#ifndef E16ANA_TRACKCHECKFILE_HH
#define E16ANA_TRACKCHECKFILE_HH

#include <array>
#include <iostream>
#include <vector>

#include "TVector3.h"
#include "E16ANA_TrackCandidate.hh"

#include "TFile.h"
#include "TGraph.h"
#include "TH1.h"
#include "TTree.h"

class E16ANA_TrackCheckFile {
 public:
  E16ANA_TrackCheckFile(char* file_name = "tmp.root")
      : file(TFile(file_name, "recreate")) {
    t_param = new TTree("param", "param");
    tree = new TTree("tree", "tree");
    // Hit, Cluster
    t_param->Branch("sigma", &sigma);
    t_param->Branch("init_pos_error", &init_pos_error);
    t_param->Branch("tracking_max_steps", &tracking_max_steps, "tracking_max_steps/I");
    t_param->Branch("projection_max_steps", &projection_max_steps, "projection_max_steps/I");
    t_param->Branch("gtr_time_difference_threshold", gtr_time_difference_threshold, "projection_max_steps[3]/I");
    t_param->Branch("x_sigma", x_sigma, "x_sigma[5]/D");
    t_param->Branch("y_sigma", y_sigma, "y_sigma[3]/D");
    t_param->Branch("min_hits_in_x_cluster", &min_hits_in_x_cluster, "min_hits_in_x_cluster/I");
    t_param->Branch("gtr_y_diff_threshold", &gtr_y_diff_threshold, "gtr_y_diff_threshold/D");
    t_param->Branch("gtr_peak_sum_threshold_x", gtr_peak_sum_threshold_x, "gtr_peak_sum_threshold_x[3]/D");
    t_param->Branch("gtr_peak_sum_threshold_y", &gtr_peak_sum_threshold_y, "gtr_peak_sum_threshold_y/D");
    t_param->Branch("raugh_fit_chi_square_threshold", raugh_fit_chi_square_threshold, "raugh_fit_chi_square_threshold[2]/D");
    t_param->Branch("raugh_x_fit_coefficient_threhold", raugh_x_fit_coefficient_threhold, "raugh_x_fit_coefficient_threhold[3]/D");
    t_param->Branch("raugh_y_fit_coefficient_threhold", raugh_y_fit_coefficient_threhold, "raugh_y_fit_coefficient_threhold[2]/D");
    t_param->Branch("hbd_projection_threshold", &hbd_projection_threshold, "hbd_projection_threshold/D");
    t_param->Branch("lg_projection_threshold", &lg_projection_threshold, "lg_projection_threshold/D");
    t_param->Branch("vtx_square_threshold", &vtx_square_threshold, "vtx_square_threshold/D");
    t_param->Branch("step_track_step_size_cm", &step_track_step_size_cm, "step_track_step_size_cm/D");
    t_param->Branch("step_track_array_size", &step_track_array_size, "step_track_array_size/I");
    
    tree->Branch("event_id", &event_id, "event_id/I");
    tree->Branch("n_ssd_clusters", &n_ssd_clusters, "n_ssd_clusters/I");
    tree->Branch("ssd_cluster_mid", &ssd_cluster_mid);
    tree->Branch("ssd_cluster_x",   &ssd_cluster_x);
    tree->Branch("ssd_cluster_gx",  &ssd_cluster_gx);
    tree->Branch("ssd_cluster_gz",  &ssd_cluster_gz);
    tree->Branch("n_gtr100x_clusters", &n_gtr100x_clusters, "n_gtr100x_clusters/I");
    tree->Branch("gtr100x_cluster_mid", &gtr100x_cluster_mid);
    tree->Branch("gtr100x_cluster_x",   &gtr100x_cluster_x);
    tree->Branch("gtr100x_cluster_gx",  &gtr100x_cluster_gx);
    tree->Branch("gtr100x_cluster_gz",  &gtr100x_cluster_gz);
    tree->Branch("n_gtr200x_clusters", &n_gtr200x_clusters, "n_gtr200x_clusters/I");
    tree->Branch("gtr200x_cluster_mid", &gtr200x_cluster_mid);
    tree->Branch("gtr200x_cluster_x",   &gtr200x_cluster_x);
    tree->Branch("gtr200x_cluster_gx",  &gtr200x_cluster_gx);
    tree->Branch("gtr200x_cluster_gz",  &gtr200x_cluster_gz);
    tree->Branch("n_gtr300x_clusters", &n_gtr300x_clusters, "n_gtr300x_clusters/I");
    tree->Branch("gtr300x_cluster_mid", &gtr300x_cluster_mid);
    tree->Branch("gtr300x_cluster_x",   &gtr300x_cluster_x);
    tree->Branch("gtr300x_cluster_gx",  &gtr300x_cluster_gx);
    tree->Branch("gtr300x_cluster_gz",  &gtr300x_cluster_gz);
    tree->Branch("n_gtr100y_clusters", &n_gtr100y_clusters, "n_gtr100y_clusters/I");
    tree->Branch("gtr100y_cluster_mid", &gtr100y_cluster_mid);
    tree->Branch("gtr100x_cluster_y",   &gtr100x_cluster_y);
    tree->Branch("gtr100y_cluster_gy",  &gtr100y_cluster_gy);
    tree->Branch("gtr100y_cluster_gr",  &gtr100y_cluster_gr);
    tree->Branch("n_gtr100yb_clusters", &n_gtr100yb_clusters, "n_gtr100yb_clusters/I");
    tree->Branch("gtr100yb_cluster_mid", &gtr100yb_cluster_mid);
    tree->Branch("gtr100yb_cluster_x",   &gtr100yb_cluster_x);
    tree->Branch("gtr100yb_cluster_gy",  &gtr100yb_cluster_gy);
    tree->Branch("gtr100yb_cluster_gr",  &gtr100yb_cluster_gr);
    tree->Branch("n_gtr200y_clusters", &n_gtr200y_clusters, "n_gtr200y_clusters/I");
    tree->Branch("gtr200y_cluster_mid", &gtr200y_cluster_mid);
    tree->Branch("gtr200x_cluster_y",   &gtr200x_cluster_y);
    tree->Branch("gtr200y_cluster_gy",  &gtr200y_cluster_gy);
    tree->Branch("gtr200y_cluster_gr",  &gtr200y_cluster_gr);
    tree->Branch("n_gtr300y_clusters", &n_gtr300y_clusters, "n_gtr300y_clusters/I");
    tree->Branch("gtr300y_cluster_mid", &gtr300y_cluster_mid);
    tree->Branch("gtr300x_cluster_y",   &gtr300x_cluster_y);
    tree->Branch("gtr300y_cluster_gy",  &gtr300y_cluster_gy);
    tree->Branch("gtr300y_cluster_gr",  &gtr300y_cluster_gr);
    tree->Branch("n_hbd_clusters", &n_hbd_clusters, "n_hbd_clusters/I");
    tree->Branch("hbd_cluster_mid", &hbd_cluster_mid);
    tree->Branch("hbd_cluster_x",   &hbd_cluster_x);
    tree->Branch("hbd_cluster_y",   &hbd_cluster_y);
    tree->Branch("hbd_cluster_gx",  &hbd_cluster_gx);
    tree->Branch("hbd_cluster_gy",  &hbd_cluster_gy);
    tree->Branch("hbd_cluster_gz",  &hbd_cluster_gz);
    tree->Branch("n_lg_hits", &n_lg_hits, "n_lg_hits/I");
    tree->Branch("lg_hit_mid",  &lg_hit_mid);
    tree->Branch("lg_hit_x",    &lg_hit_x);
    tree->Branch("lg_hit_y",    &lg_hit_y);
    tree->Branch("lg_hit_gx",   &lg_hit_gx);
    tree->Branch("lg_hit_gy",   &lg_hit_gy);
    tree->Branch("lg_hit_gz",   &lg_hit_gz);
    tree->Branch("lg_hit_time", &lg_hit_time);
    // Track
    tree->Branch("n_x_cands", &n_x_cands, "n_x_cands/I");
    tree->Branch("n_y_cands", &n_y_cands, "n_y_cands/I");
    tree->Branch("n_cands", &n_cands, "n_cands/I");
    tree->Branch("n_selected", &n_selected, "n_selected/I");
    tree->Branch("n_pairs", &n_pairs, "n_pairs/I");
    tree->Branch("is_selected", &is_selected);
    tree->Branch("x_raugh_fit_chi_square", &x_raugh_fit_chi_square);
    tree->Branch("x_raugh_fit_coef0", &x_raugh_fit_coef0);
    tree->Branch("x_raugh_fit_coef1", &x_raugh_fit_coef1);
    tree->Branch("x_raugh_fit_coef2", &x_raugh_fit_coef2);
    tree->Branch("y_raugh_fit_chi_square", &y_raugh_fit_chi_square);
    tree->Branch("y_raugh_fit_coef0", &y_raugh_fit_coef0);
    tree->Branch("y_raugh_fit_coef1", &y_raugh_fit_coef1);
    tree->Branch("chi_square", &chi_square);
    tree->Branch("n_steps", &n_steps);
    tree->Branch("n_calls", &n_calls);
    tree->Branch("rk_hit_init_mom_gx", &rk_hit_init_mom_gx);
    tree->Branch("rk_hit_init_mom_gy", &rk_hit_init_mom_gy);
    tree->Branch("rk_hit_init_mom_gz", &rk_hit_init_mom_gz);
    tree->Branch("rk_hit_init_pos_gx", &rk_hit_init_pos_gx);
    tree->Branch("rk_hit_init_pos_gy", &rk_hit_init_pos_gy);
    tree->Branch("rk_hit_init_pos_gz", &rk_hit_init_pos_gz);
    tree->Branch("rk_hit_ssd_gx", &rk_hit_ssd_gx);
    tree->Branch("rk_hit_ssd_gy", &rk_hit_ssd_gy);
    tree->Branch("rk_hit_ssd_gz", &rk_hit_ssd_gz);
    tree->Branch("rk_hit_gtr100_gx", &rk_hit_gtr100_gx);
    tree->Branch("rk_hit_gtr100_gy", &rk_hit_gtr100_gy);
    tree->Branch("rk_hit_gtr100_gz", &rk_hit_gtr100_gz);
    tree->Branch("rk_hit_gtr200_gx", &rk_hit_gtr200_gx);
    tree->Branch("rk_hit_gtr200_gy", &rk_hit_gtr200_gy);
    tree->Branch("rk_hit_gtr200_gz", &rk_hit_gtr200_gz);
    tree->Branch("rk_hit_gtr300_gx", &rk_hit_gtr300_gx);
    tree->Branch("rk_hit_gtr300_gy", &rk_hit_gtr300_gy);
    tree->Branch("rk_hit_gtr300_gz", &rk_hit_gtr300_gz);
    tree->Branch("rk_fit_init_mom_gx", &rk_fit_init_mom_gx);
    tree->Branch("rk_fit_init_mom_gy", &rk_fit_init_mom_gy);
    tree->Branch("rk_fit_init_mom_gz", &rk_fit_init_mom_gz);
    tree->Branch("rk_fit_init_pos_gx", &rk_fit_init_pos_gx);
    tree->Branch("rk_fit_init_pos_gy", &rk_fit_init_pos_gy);
    tree->Branch("rk_fit_init_pos_gz", &rk_fit_init_pos_gz);
    tree->Branch("rk_fit_ssd_mid", &rk_fit_ssd_mid);
    tree->Branch("rk_fit_ssd_gx",  &rk_fit_ssd_gx);
    tree->Branch("rk_fit_ssd_gy",  &rk_fit_ssd_gy);
    tree->Branch("rk_fit_ssd_gz",  &rk_fit_ssd_gz);
    tree->Branch("rk_fit_gtr100_mid", &rk_fit_gtr100_mid);
    tree->Branch("rk_fit_gtr100_gx",  &rk_fit_gtr100_gx);
    tree->Branch("rk_fit_gtr100_gy",  &rk_fit_gtr100_gy);
    tree->Branch("rk_fit_gtr100_gz",  &rk_fit_gtr100_gz);
    tree->Branch("rk_fit_gtr200_mid", &rk_fit_gtr200_mid);
    tree->Branch("rk_fit_gtr200_gx",  &rk_fit_gtr200_gx);
    tree->Branch("rk_fit_gtr200_gy",  &rk_fit_gtr200_gy);
    tree->Branch("rk_fit_gtr200_gz",  &rk_fit_gtr200_gz);
    tree->Branch("rk_fit_gtr300_mid", &rk_fit_gtr300_mid);
    tree->Branch("rk_fit_gtr300_gx",  &rk_fit_gtr300_gx);
    tree->Branch("rk_fit_gtr300_gy",  &rk_fit_gtr300_gy);
    tree->Branch("rk_fit_gtr300_gz",  &rk_fit_gtr300_gz);
    tree->Branch("rk_fit_hbd_mid", &rk_fit_hbd_mid);
    tree->Branch("rk_fit_hbd_x",   &rk_fit_hbd_x);
    tree->Branch("rk_fit_hbd_y",   &rk_fit_hbd_y);
    tree->Branch("rk_fit_hbd_gx",  &rk_fit_hbd_gx);
    tree->Branch("rk_fit_hbd_gy",  &rk_fit_hbd_gy);
    tree->Branch("rk_fit_hbd_gz",  &rk_fit_hbd_gz);
    tree->Branch("rk_fit_lg_c_mid", &rk_fit_lg_c_mid);
    tree->Branch("rk_fit_lg_c_x",   &rk_fit_lg_c_x);
    tree->Branch("rk_fit_lg_c_y",   &rk_fit_lg_c_y);
    tree->Branch("rk_fit_lg_c_gx",  &rk_fit_lg_c_gx);
    tree->Branch("rk_fit_lg_c_gy",  &rk_fit_lg_c_gy);
    tree->Branch("rk_fit_lg_c_gz",  &rk_fit_lg_c_gz);
    tree->Branch("rk_fit_lg_b_mid", &rk_fit_lg_b_mid);
    tree->Branch("rk_fit_lg_b_x",   &rk_fit_lg_b_x);
    tree->Branch("rk_fit_lg_b_y",   &rk_fit_lg_b_y);
    tree->Branch("rk_fit_lg_b_gx",  &rk_fit_lg_b_gx);
    tree->Branch("rk_fit_lg_b_gy",  &rk_fit_lg_b_gy);
    tree->Branch("rk_fit_lg_b_gz",  &rk_fit_lg_b_gz);
    tree->Branch("rk_fit_lg_a_mid", &rk_fit_lg_a_mid);
    tree->Branch("rk_fit_lg_a_x",   &rk_fit_lg_a_x);
    tree->Branch("rk_fit_lg_a_y",   &rk_fit_lg_a_y);
    tree->Branch("rk_fit_lg_a_gx",  &rk_fit_lg_a_gx);
    tree->Branch("rk_fit_lg_a_gy",  &rk_fit_lg_a_gy);
    tree->Branch("rk_fit_lg_a_gz",  &rk_fit_lg_a_gz);
    tree->Branch("rk_res_ssd_x", &rk_res_ssd_x);
    tree->Branch("rk_res_gtr100_x", &rk_res_gtr100_x);
    tree->Branch("rk_res_gtr100_y", &rk_res_gtr100_y);
    tree->Branch("rk_res_gtr200_x", &rk_res_gtr200_x);
    tree->Branch("rk_res_gtr200_y", &rk_res_gtr200_y);
    tree->Branch("rk_res_gtr300_x", &rk_res_gtr300_x);
    tree->Branch("rk_res_gtr300_y", &rk_res_gtr300_y);
    tree->Branch("rk_proj_tgt0_gx", &rk_proj_tgt0_gx);
    tree->Branch("rk_proj_tgt0_gy", &rk_proj_tgt0_gy);
    tree->Branch("rk_proj_tgt0_gz", &rk_proj_tgt0_gz);
    tree->Branch("rk_proj_tgt1_gx", &rk_proj_tgt1_gx);
    tree->Branch("rk_proj_tgt1_gy", &rk_proj_tgt1_gy);
    tree->Branch("rk_proj_tgt1_gz", &rk_proj_tgt1_gz);
    tree->Branch("rk_proj_tgt2_gx", &rk_proj_tgt2_gx);
    tree->Branch("rk_proj_tgt2_gy", &rk_proj_tgt2_gy);
    tree->Branch("rk_proj_tgt2_gz", &rk_proj_tgt2_gz);
    tree->Branch("rk_proj_tgt_mom0_gx", &rk_proj_tgt_mom0_gx);
    tree->Branch("rk_proj_tgt_mom0_gy", &rk_proj_tgt_mom0_gy);
    tree->Branch("rk_proj_tgt_mom0_gz", &rk_proj_tgt_mom0_gz);
    tree->Branch("rk_proj_tgt_mom1_gx", &rk_proj_tgt_mom1_gx);
    tree->Branch("rk_proj_tgt_mom1_gy", &rk_proj_tgt_mom1_gy);
    tree->Branch("rk_proj_tgt_mom1_gz", &rk_proj_tgt_mom1_gz);
    tree->Branch("rk_proj_tgt_mom2_gx", &rk_proj_tgt_mom2_gx);
    tree->Branch("rk_proj_tgt_mom2_gy", &rk_proj_tgt_mom2_gy);
    tree->Branch("rk_proj_tgt_mom2_gz", &rk_proj_tgt_mom2_gz);
    tree->Branch("rk_proj_hbd0_mid", &rk_proj_hbd0_mid);
    tree->Branch("rk_proj_hbd0_x",   &rk_proj_hbd0_x);
    tree->Branch("rk_proj_hbd0_y",   &rk_proj_hbd0_y);
    tree->Branch("rk_proj_hbd1_mid", &rk_proj_hbd1_mid);
    tree->Branch("rk_proj_hbd1_x",   &rk_proj_hbd1_x);
    tree->Branch("rk_proj_hbd1_y",   &rk_proj_hbd1_y);
    tree->Branch("rk_proj_hbd2_mid", &rk_proj_hbd2_mid);
    tree->Branch("rk_proj_hbd2_x",   &rk_proj_hbd2_x);
    tree->Branch("rk_proj_hbd2_y",   &rk_proj_hbd2_y);
    tree->Branch("rk_proj_hbd3_mid", &rk_proj_hbd3_mid);
    tree->Branch("rk_proj_hbd3_x",   &rk_proj_hbd3_x);
    tree->Branch("rk_proj_hbd3_y",   &rk_proj_hbd3_y);
    tree->Branch("rk_proj_lg0_mid", &rk_proj_lg0_mid);
    tree->Branch("rk_proj_lg0_x",   &rk_proj_lg0_x);
    tree->Branch("rk_proj_lg0_y",   &rk_proj_lg0_y);
    tree->Branch("rk_proj_lg1_mid", &rk_proj_lg1_mid);
    tree->Branch("rk_proj_lg1_x",   &rk_proj_lg1_x);
    tree->Branch("rk_proj_lg1_y",   &rk_proj_lg1_y);
    tree->Branch("rk_proj_lg2_mid", &rk_proj_lg2_mid);
    tree->Branch("rk_proj_lg2_x",   &rk_proj_lg2_x);
    tree->Branch("rk_proj_lg2_y",   &rk_proj_lg2_y);
    tree->Branch("rk_proj_lg3_mid", &rk_proj_lg3_mid);
    tree->Branch("rk_proj_lg3_x",   &rk_proj_lg3_x);
    tree->Branch("rk_proj_lg3_y",   &rk_proj_lg3_y);
    tree->Branch("rk_vtx_gx", &rk_vtx_gx);
    tree->Branch("rk_vtx_gy", &rk_vtx_gy);
    tree->Branch("rk_vtx_gz", &rk_vtx_gz);
  };
  ~E16ANA_TrackCheckFile() { file.Write(); }
  void AddParam(E16ANA_TrackCandidates& cands) {
    auto& cand = cands.TrackCandidate(0);
    sigma = cand.Sigma();
    init_pos_error = cand.InitPosError();
    tracking_max_steps = cand.TrackingMaxSteps();
    projection_max_steps = cand.ProjectionMaxSteps();
    for (int i = 0; i < 3; ++i) {
      gtr_time_difference_threshold[i] = cands.GTRTimeDiffThreshold(i);
    }
    for (int i = 0; i < 5; ++i) {
      x_sigma[i] = cands.XSigma(i);
    }
    for (int i = 0; i < 3; ++i) {
      y_sigma[i] = cands.YSigma(i);
    }
    min_hits_in_x_cluster = cands.MinHitsInXCluster();
    gtr_y_diff_threshold = cands.GTRYDiffThreshold();
    for (int i = 0; i < 3; ++i) {
      gtr_peak_sum_threshold_x[i] = cands.GTRPeakSumThresholdX(i);
    }
    gtr_peak_sum_threshold_y= cands.GTRPeakSumThresholdY();
    for (int i = 0; i < 2; ++i) {
      raugh_fit_chi_square_threshold[i] = cands.RaughFitChiSquareThreshold(i);
    }
    for (int i = 0; i < 3; ++i) {
      raugh_x_fit_coefficient_threhold[i] = cands.RaughXFitCoefficientThreshold(i);
    }
    for (int i = 0; i < 2; ++i) {
      raugh_y_fit_coefficient_threhold[i] = cands.RaughYFitCoefficientThreshold(i);
    }
    hbd_projection_threshold = cands.HBDProjectionThreshold();
    lg_projection_threshold = cands.LGProjectionThreshold();
    vtx_square_threshold = cands.VertexSquareThreshold();
    step_track_step_size_cm = cands.StepTrackStepSizeCm();
    step_track_array_size= cands.StepTrackArraySize();
    t_param->Fill();
  }
  void AddEntry(int _event_id, E16ANA_GeometryV2& geometry, E16DST_DST1PhysicsRecord& record, E16ANA_TrackCandidates& cands) {
    event_id = _event_id;
    AddRecord(geometry, record);
    AddCandidate(geometry, cands);
    tree->Fill();
  }
 private:
  void AddRecord(E16ANA_GeometryV2& geometry, E16DST_DST1PhysicsRecord& record) {
    n_ssd_clusters = record.SSD().NumClusters();
    ssd_cluster_mid.resize(n_ssd_clusters);
    ssd_cluster_x.resize(n_ssd_clusters);
    ssd_cluster_gx.resize(n_ssd_clusters);
    ssd_cluster_gz.resize(n_ssd_clusters);
    for (int i = 0; i < n_ssd_clusters; ++i) {
      auto& clst = record.SSD().Cluster(i);
      ssd_cluster_mid[i] = clst.ModuleId();
      ssd_cluster_x[i] = clst.LocalX();
      auto gpos = clst.GlobalPos(geometry);
      ssd_cluster_gx[i] = gpos.X();
      ssd_cluster_gz[i] = gpos.Z();
    }
    n_gtr100x_clusters = 0;
    n_gtr200x_clusters = 0;
    n_gtr300x_clusters = 0;
    n_gtr100y_clusters = 0;
    n_gtr100yb_clusters = 0;
    n_gtr200y_clusters = 0;
    n_gtr300y_clusters = 0;
    gtr100x_cluster_mid.clear();
    gtr100x_cluster_x.clear();
    gtr100x_cluster_gx.clear();
    gtr100x_cluster_gz.clear();
    gtr200x_cluster_mid.clear();
    gtr200x_cluster_x.clear();
    gtr200x_cluster_gx.clear();
    gtr200x_cluster_gz.clear();
    gtr300x_cluster_mid.clear();
    gtr300x_cluster_x.clear();
    gtr300x_cluster_gx.clear();
    gtr300x_cluster_gz.clear();
    gtr100y_cluster_mid.clear();
    gtr100x_cluster_y.clear();
    gtr100y_cluster_gy.clear();
    gtr100y_cluster_gr.clear();
    gtr100yb_cluster_mid.clear();
    gtr100yb_cluster_x.clear();
    gtr100yb_cluster_gy.clear();
    gtr100yb_cluster_gr.clear();
    gtr200y_cluster_mid.clear();
    gtr200x_cluster_y.clear();
    gtr200y_cluster_gy.clear();
    gtr200y_cluster_gr.clear();
    gtr300y_cluster_mid.clear();
    gtr300x_cluster_y.clear();
    gtr300y_cluster_gy.clear();
    gtr300y_cluster_gr.clear();
    auto n_gtr_clusters = record.GTR().NumClusters();
    for (int i = 0; i < n_gtr_clusters; ++i) {
      auto& clst = record.GTR().Cluster(i);
      auto lid = clst.LayerId();
      auto type = clst.Type();
      if (lid == 0) {
        if (type == 0) {
          ++n_gtr100x_clusters;
          gtr100x_cluster_mid.emplace_back(clst.ModuleId());
          gtr100x_cluster_x.emplace_back(clst.LocalX());
          auto gpos = clst.GlobalPos(geometry);
          gtr100x_cluster_gx.emplace_back(gpos.X());
          gtr100x_cluster_gz.emplace_back(gpos.Z());
        } else if (type == 1) {
          ++n_gtr100y_clusters;
          gtr100y_cluster_mid.emplace_back(clst.ModuleId());
          gtr100x_cluster_y.emplace_back(clst.LocalX());
          auto gpos = clst.GlobalPos(geometry);
          gtr100y_cluster_gy.emplace_back(gpos.X());
          gtr100y_cluster_gr.emplace_back(gpos.Z());
        } else {
          ++n_gtr100yb_clusters;
          gtr100yb_cluster_mid.emplace_back(clst.ModuleId());
          gtr100yb_cluster_x.emplace_back(clst.LocalX());
          auto gpos = clst.GlobalPos(geometry);
          gtr100yb_cluster_gy.emplace_back(gpos.X());
          gtr100yb_cluster_gr.emplace_back(gpos.Z());
        }
      } else if (lid == 1) {
        if (type == 0) {
          ++n_gtr200x_clusters;
          gtr200x_cluster_mid.emplace_back(clst.ModuleId());
          gtr200x_cluster_x.emplace_back(clst.LocalX());
          auto gpos = clst.GlobalPos(geometry);
          gtr200x_cluster_gx.emplace_back(gpos.X());
          gtr200x_cluster_gz.emplace_back(gpos.Z());
        } else if (type == 1) {
          ++n_gtr200y_clusters;
          gtr200y_cluster_mid.emplace_back(clst.ModuleId());
          gtr200x_cluster_y.emplace_back(clst.LocalX());
          auto gpos = clst.GlobalPos(geometry);
          gtr200y_cluster_gy.emplace_back(gpos.X());
          gtr200y_cluster_gr.emplace_back(gpos.Z());
        }
      } else {
        if (type == 0) {
          ++n_gtr300x_clusters;
          gtr300x_cluster_mid.emplace_back(clst.ModuleId());
          gtr300x_cluster_x.emplace_back(clst.LocalX());
          auto gpos = clst.GlobalPos(geometry);
          gtr300x_cluster_gx.emplace_back(gpos.X());
          gtr300x_cluster_gz.emplace_back(gpos.Z());
        } else if (type == 1) {
          ++n_gtr300y_clusters;
          gtr300y_cluster_mid.emplace_back(clst.ModuleId());
          gtr300x_cluster_y.emplace_back(clst.LocalX());
          auto gpos = clst.GlobalPos(geometry);
          gtr300y_cluster_gy.emplace_back(gpos.X());
          gtr300y_cluster_gr.emplace_back(gpos.Z());
        }
      }
    }
    n_hbd_clusters = record.HBD().NumClusters();
    hbd_cluster_mid.resize(n_hbd_clusters);
    hbd_cluster_x.resize(n_hbd_clusters);
    hbd_cluster_y.resize(n_hbd_clusters);
    hbd_cluster_gx.resize(n_hbd_clusters);
    hbd_cluster_gy.resize(n_hbd_clusters);
    hbd_cluster_gz.resize(n_hbd_clusters);
    for (int i = 0; i < n_hbd_clusters; ++i) {
      auto& clst = record.HBD().Cluster(i);
      hbd_cluster_mid[i] = clst.ModuleId();
      auto lpos = clst.LocalPos();
      hbd_cluster_x[i] = lpos.X();
      hbd_cluster_y[i] = lpos.Y();
      auto gpos = clst.GlobalPos(geometry);
      hbd_cluster_gx[i] = gpos.X();
      hbd_cluster_gy[i] = gpos.Y();
      hbd_cluster_gz[i] = gpos.Z();
    }
    n_lg_hits = record.LG().NumHits();
    lg_hit_mid.resize(n_lg_hits);
    lg_hit_x.resize(n_lg_hits);
    lg_hit_y.resize(n_lg_hits);
    lg_hit_gx.resize(n_lg_hits);
    lg_hit_gy.resize(n_lg_hits);
    lg_hit_gz.resize(n_lg_hits);
    lg_hit_time.resize(n_lg_hits);
    for (int i = 0; i < n_lg_hits; ++i) {
      auto& hit = record.LG().Hit(i);
      lg_hit_mid[i] = hit.ModuleId();
      auto lpos = hit.LocalPos(geometry);
      lg_hit_x[i] = lpos.X();
      lg_hit_y[i] = lpos.Y();
      auto gpos = hit.GlobalPos(geometry);
      lg_hit_gx[i] = gpos.X();
      lg_hit_gy[i] = gpos.Y();
      lg_hit_gz[i] = gpos.Z();
      lg_hit_time[i] = hit.Timing();
    }
  }
  void AddCandidate(E16ANA_GeometryV2& geometry, E16ANA_TrackCandidates& cands) {
    n_x_cands = cands.NumXCandidates();
    n_y_cands = cands.NumYCandidates();
    n_cands = cands.NumTrackCandidates();
    n_selected = cands.NumSelectedTrackCandidates();
    n_pairs = cands.NumSelectedTrackCandidatePairs();
    is_selected.resize(n_cands);
    x_raugh_fit_chi_square.resize(n_cands);
    x_raugh_fit_coef0.resize(n_cands);
    x_raugh_fit_coef1.resize(n_cands);
    x_raugh_fit_coef2.resize(n_cands);
    y_raugh_fit_chi_square.resize(n_cands);
    y_raugh_fit_coef0.resize(n_cands);
    y_raugh_fit_coef1.resize(n_cands);
    chi_square.resize(n_cands);
    n_steps.resize(n_cands);
    n_calls.resize(n_cands);
    rk_hit_init_mom_gx.resize(n_cands);
    rk_hit_init_mom_gy.resize(n_cands);
    rk_hit_init_mom_gz.resize(n_cands);
    rk_hit_init_pos_gx.resize(n_cands);
    rk_hit_init_pos_gy.resize(n_cands);
    rk_hit_init_pos_gz.resize(n_cands);
    rk_hit_ssd_gx.resize(n_cands);
    rk_hit_ssd_gy.resize(n_cands);
    rk_hit_ssd_gz.resize(n_cands);
    rk_hit_gtr100_gx.resize(n_cands);
    rk_hit_gtr100_gy.resize(n_cands);
    rk_hit_gtr100_gz.resize(n_cands);
    rk_hit_gtr200_gx.resize(n_cands);
    rk_hit_gtr200_gy.resize(n_cands);
    rk_hit_gtr200_gz.resize(n_cands);
    rk_hit_gtr300_gx.resize(n_cands);
    rk_hit_gtr300_gy.resize(n_cands);
    rk_hit_gtr300_gz.resize(n_cands);
    rk_fit_init_mom_gx.resize(n_cands);
    rk_fit_init_mom_gy.resize(n_cands);
    rk_fit_init_mom_gz.resize(n_cands);
    rk_fit_init_pos_gx.resize(n_cands);
    rk_fit_init_pos_gy.resize(n_cands);
    rk_fit_init_pos_gz.resize(n_cands);
    rk_fit_ssd_mid.resize(n_cands);
    rk_fit_ssd_gx.resize(n_cands);
    rk_fit_ssd_gy.resize(n_cands);
    rk_fit_ssd_gz.resize(n_cands);
    rk_fit_gtr100_mid.resize(n_cands);
    rk_fit_gtr100_gx.resize(n_cands);
    rk_fit_gtr100_gy.resize(n_cands);
    rk_fit_gtr100_gz.resize(n_cands);
    rk_fit_gtr200_mid.resize(n_cands);
    rk_fit_gtr200_gx.resize(n_cands);
    rk_fit_gtr200_gy.resize(n_cands);
    rk_fit_gtr200_gz.resize(n_cands);
    rk_fit_gtr300_mid.resize(n_cands);
    rk_fit_gtr300_gx.resize(n_cands);
    rk_fit_gtr300_gy.resize(n_cands);
    rk_fit_gtr300_gz.resize(n_cands);
    rk_fit_hbd_mid.resize(n_cands);
    rk_fit_hbd_x.resize(n_cands);
    rk_fit_hbd_y.resize(n_cands);
    rk_fit_hbd_gx.resize(n_cands);
    rk_fit_hbd_gy.resize(n_cands);
    rk_fit_hbd_gz.resize(n_cands);
    rk_fit_lg_c_mid.resize(n_cands);
    rk_fit_lg_c_x.resize(n_cands);
    rk_fit_lg_c_y.resize(n_cands);
    rk_fit_lg_c_gx.resize(n_cands);
    rk_fit_lg_c_gy.resize(n_cands);
    rk_fit_lg_c_gz.resize(n_cands);
    rk_fit_lg_b_mid.resize(n_cands);
    rk_fit_lg_b_x.resize(n_cands);
    rk_fit_lg_b_y.resize(n_cands);
    rk_fit_lg_b_gx.resize(n_cands);
    rk_fit_lg_b_gy.resize(n_cands);
    rk_fit_lg_b_gz.resize(n_cands);
    rk_fit_lg_a_mid.resize(n_cands);
    rk_fit_lg_a_x.resize(n_cands);
    rk_fit_lg_a_y.resize(n_cands);
    rk_fit_lg_a_gx.resize(n_cands);
    rk_fit_lg_a_gy.resize(n_cands);
    rk_fit_lg_a_gz.resize(n_cands);
    rk_res_ssd_x.resize(n_cands);
    rk_res_gtr100_x.resize(n_cands);
    rk_res_gtr100_y.resize(n_cands);
    rk_res_gtr200_x.resize(n_cands);
    rk_res_gtr200_y.resize(n_cands);
    rk_res_gtr300_x.resize(n_cands);
    rk_res_gtr300_y.resize(n_cands);
    rk_proj_tgt0_gx.resize(n_cands);
    rk_proj_tgt0_gy.resize(n_cands);
    rk_proj_tgt0_gz.resize(n_cands);
    rk_proj_tgt1_gx.resize(n_cands);
    rk_proj_tgt1_gy.resize(n_cands);
    rk_proj_tgt1_gz.resize(n_cands);
    rk_proj_tgt2_gx.resize(n_cands);
    rk_proj_tgt2_gy.resize(n_cands);
    rk_proj_tgt2_gz.resize(n_cands);
    rk_proj_tgt_mom0_gx.resize(n_cands);
    rk_proj_tgt_mom0_gy.resize(n_cands);
    rk_proj_tgt_mom0_gz.resize(n_cands);
    rk_proj_tgt_mom1_gx.resize(n_cands);
    rk_proj_tgt_mom1_gy.resize(n_cands);
    rk_proj_tgt_mom1_gz.resize(n_cands);
    rk_proj_tgt_mom2_gx.resize(n_cands);
    rk_proj_tgt_mom2_gy.resize(n_cands);
    rk_proj_tgt_mom2_gz.resize(n_cands);
    rk_proj_hbd0_mid.resize(n_cands);
    rk_proj_hbd0_x.resize(n_cands);
    rk_proj_hbd0_y.resize(n_cands);
    rk_proj_hbd1_mid.resize(n_cands);
    rk_proj_hbd1_x.resize(n_cands);
    rk_proj_hbd1_y.resize(n_cands);
    rk_proj_hbd2_mid.resize(n_cands);
    rk_proj_hbd2_x.resize(n_cands);
    rk_proj_hbd2_y.resize(n_cands);
    rk_proj_hbd3_mid.resize(n_cands);
    rk_proj_hbd3_x.resize(n_cands);
    rk_proj_hbd3_y.resize(n_cands);
    rk_proj_lg0_mid.resize(n_cands);
    rk_proj_lg0_x.resize(n_cands);
    rk_proj_lg0_y.resize(n_cands);
    rk_proj_lg1_mid.resize(n_cands);
    rk_proj_lg1_x.resize(n_cands);
    rk_proj_lg1_y.resize(n_cands);
    rk_proj_lg2_mid.resize(n_cands);
    rk_proj_lg2_x.resize(n_cands);
    rk_proj_lg2_y.resize(n_cands);
    rk_proj_lg3_mid.resize(n_cands);
    rk_proj_lg3_x.resize(n_cands);
    rk_proj_lg3_y.resize(n_cands);
    rk_vtx_gx.resize(n_pairs);
    rk_vtx_gy.resize(n_pairs);
    rk_vtx_gz.resize(n_pairs);
    for (int i = 0; i < n_cands; ++i) {
      auto& cand = cands.TrackCandidates()[i];
      is_selected[i] = cand.IsSelected();
      chi_square[i] = cand.ChiSquare();
      n_steps[i] = cand.NumSteps();
      n_calls[i] = cand.NumCalls();
      x_raugh_fit_chi_square[i] = cand.XChiSquare();
      x_raugh_fit_coef0[i] = cand.XCoef(0);
      x_raugh_fit_coef1[i] = cand.XCoef(1);
      x_raugh_fit_coef2[i] = cand.XCoef(2);
      y_raugh_fit_chi_square[i] = cand.YChiSquare();
      y_raugh_fit_coef0[i] = cand.YCoef(0);
      y_raugh_fit_coef1[i] = cand.YCoef(1);
      auto hit_init_mom = cand.InitMom();
      auto hit_init_pos = cand.InitPos();
      rk_hit_init_mom_gx[i] = hit_init_mom.X();
      rk_hit_init_mom_gy[i] = hit_init_mom.Y();
      rk_hit_init_mom_gz[i] = hit_init_mom.Z();
      rk_hit_init_pos_gx[i] = hit_init_pos.X();
      rk_hit_init_pos_gy[i] = hit_init_pos.Y();
      rk_hit_init_pos_gz[i] = hit_init_pos.Z();
      auto& pairs = cand.ClusterPairs();
      auto& ssdhit_gpos = pairs[0].GlobalPos();
      rk_hit_ssd_gx[i] = ssdhit_gpos.X();
      rk_hit_ssd_gy[i] = ssdhit_gpos.Y();
      rk_hit_ssd_gz[i] = ssdhit_gpos.Z();
      auto& gtr100hit_gpos = pairs[1].GlobalPos();
      rk_hit_gtr100_gx[i] = gtr100hit_gpos.X();
      rk_hit_gtr100_gy[i] = gtr100hit_gpos.Y();
      rk_hit_gtr100_gz[i] = gtr100hit_gpos.Z();
      auto& gtr200hit_gpos = pairs[2].GlobalPos();
      rk_hit_gtr200_gx[i] = gtr200hit_gpos.X();
      rk_hit_gtr200_gy[i] = gtr200hit_gpos.Y();
      rk_hit_gtr200_gz[i] = gtr200hit_gpos.Z();
      auto& gtr300hit_gpos = pairs[3].GlobalPos();
      rk_hit_gtr300_gx[i] = gtr300hit_gpos.X();
      rk_hit_gtr300_gy[i] = gtr300hit_gpos.Y();
      rk_hit_gtr300_gz[i] = gtr300hit_gpos.Z();
      auto fit_init_mom = cand.FitInitMom();
      rk_fit_init_mom_gx[i] = fit_init_mom.X();
      rk_fit_init_mom_gy[i] = fit_init_mom.Y();
      rk_fit_init_mom_gz[i] = fit_init_mom.Z();
      auto fit_init_pos = cand.FitInitPos();
      rk_fit_init_pos_gx[i] = fit_init_pos.X();
      rk_fit_init_pos_gy[i] = fit_init_pos.Y();
      rk_fit_init_pos_gz[i] = fit_init_pos.Z();
      const auto& fits = cand.LocalFitResults();
      rk_fit_ssd_mid[i] = fits[0].module_id;
      auto& ssdfit_gpos = fits[0].global_pos;
      rk_fit_ssd_gx[i] = ssdfit_gpos.X();
      rk_fit_ssd_gy[i] = ssdfit_gpos.Y();
      rk_fit_ssd_gz[i] = ssdfit_gpos.Z();
      rk_res_ssd_x[i] = fits[0].residual_pos.X();
      rk_fit_gtr100_mid[i] = fits[1].module_id;
      auto& gtr100fit_gpos = fits[1].global_pos;
      rk_fit_gtr100_gx[i] = gtr100fit_gpos.X();
      rk_fit_gtr100_gy[i] = gtr100fit_gpos.Y();
      rk_fit_gtr100_gz[i] = gtr100fit_gpos.Z();
      rk_res_gtr100_x[i] = fits[1].residual_pos.X();
      rk_res_gtr100_y[i] = fits[1].residual_pos.Y();
      rk_fit_gtr200_mid[i] = fits[2].module_id;
      auto& gtr200fit_gpos = fits[2].global_pos;
      rk_fit_gtr200_gx[i] = gtr200fit_gpos.X();
      rk_fit_gtr200_gy[i] = gtr200fit_gpos.Y();
      rk_fit_gtr200_gz[i] = gtr200fit_gpos.Z();
      rk_res_gtr200_x[i] = fits[2].residual_pos.X();
      rk_res_gtr200_y[i] = fits[2].residual_pos.Y();
      rk_fit_gtr300_mid[i] = fits[3].module_id;
      auto& gtr300fit_gpos = fits[3].global_pos;
      rk_fit_gtr300_gx[i] = gtr300fit_gpos.X();
      rk_fit_gtr300_gy[i] = gtr300fit_gpos.Y();
      rk_fit_gtr300_gz[i] = gtr300fit_gpos.Z();
      rk_res_gtr300_x[i] = fits[3].residual_pos.X();
      rk_res_gtr300_y[i] = fits[3].residual_pos.Y();
      rk_fit_hbd_mid[i] = fits[4].module_id;
      auto& hbdfit_lpos = fits[4].local_pos;
      rk_fit_hbd_x[i] = hbdfit_lpos.X();
      rk_fit_hbd_y[i] = hbdfit_lpos.Y();
      auto& hbdfit_gpos = fits[4].global_pos;
      rk_fit_hbd_gx[i] = hbdfit_gpos.X();
      rk_fit_hbd_gy[i] = hbdfit_gpos.Y();
      rk_fit_hbd_gz[i] = hbdfit_gpos.Z();
      rk_fit_lg_c_mid[i] = fits[5].module_id;
      auto& lgcfit_lpos = fits[5].local_pos;
      rk_fit_lg_c_x[i] = lgcfit_lpos.X();
      rk_fit_lg_c_y[i] = lgcfit_lpos.Y();
      auto& lgcfit_gpos = fits[5].global_pos;
      rk_fit_lg_c_gx[i] = lgcfit_gpos.X();
      rk_fit_lg_c_gy[i] = lgcfit_gpos.Y();
      rk_fit_lg_c_gz[i] = lgcfit_gpos.Z();
      rk_fit_lg_b_mid[i] = fits[6].module_id;
      auto& lgbfit_lpos = fits[6].local_pos;
      rk_fit_lg_b_x[i] = lgbfit_lpos.X();
      rk_fit_lg_b_y[i] = lgbfit_lpos.Y();
      auto& lgbfit_gpos = fits[6].global_pos;
      rk_fit_lg_b_gx[i] = lgbfit_gpos.X();
      rk_fit_lg_b_gy[i] = lgbfit_gpos.Y();
      rk_fit_lg_b_gz[i] = lgbfit_gpos.Z();
      rk_fit_lg_a_mid[i] = fits[7].module_id;
      auto& lgafit_lpos = fits[7].local_pos;
      rk_fit_lg_a_x[i] = lgafit_lpos.X();
      rk_fit_lg_a_y[i] = lgafit_lpos.Y();
      auto& lgafit_gpos = fits[7].global_pos;
      rk_fit_lg_a_gx[i] = lgafit_gpos.X();
      rk_fit_lg_a_gy[i] = lgafit_gpos.Y();
      rk_fit_lg_a_gz[i] = lgafit_gpos.Z();
      auto proj_tgt0 = cand.PosAtTarget(0);
      rk_proj_tgt0_gx[i] = proj_tgt0.X();
      rk_proj_tgt0_gy[i] = proj_tgt0.Y();
      rk_proj_tgt0_gz[i] = proj_tgt0.Z();
      auto proj_tgt1 = cand.PosAtTarget(1);
      rk_proj_tgt1_gx[i] = proj_tgt1.X();
      rk_proj_tgt1_gy[i] = proj_tgt1.Y();
      rk_proj_tgt1_gz[i] = proj_tgt1.Z();
      auto proj_tgt2 = cand.PosAtTarget(2);
      rk_proj_tgt2_gx[i] = proj_tgt2.X();
      rk_proj_tgt2_gy[i] = proj_tgt2.Y();
      rk_proj_tgt2_gz[i] = proj_tgt2.Z();
      auto proj_tgt_mom0 = cand.MomAtTarget(0);
      rk_proj_tgt_mom0_gx[i] = proj_tgt_mom0.X();
      rk_proj_tgt_mom0_gy[i] = proj_tgt_mom0.Y();
      rk_proj_tgt_mom0_gz[i] = proj_tgt_mom0.Z();
      auto proj_tgt_mom1 = cand.MomAtTarget(1);
      rk_proj_tgt_mom1_gx[i] = proj_tgt_mom1.X();
      rk_proj_tgt_mom1_gy[i] = proj_tgt_mom1.Y();
      rk_proj_tgt_mom1_gz[i] = proj_tgt_mom1.Z();
      auto proj_tgt_mom2 = cand.MomAtTarget(2);
      rk_proj_tgt_mom2_gx[i] = proj_tgt_mom2.X();
      rk_proj_tgt_mom2_gy[i] = proj_tgt_mom2.Y();
      rk_proj_tgt_mom2_gz[i] = proj_tgt_mom2.Z();
      auto& proj_hbd_clusters = cand.ProjectedHBDClusters();
      rk_proj_hbd0_mid[i] = -10000;
      rk_proj_hbd0_x[i] = -10000.;
      rk_proj_hbd0_y[i] = -10000.;
      rk_proj_hbd1_mid[i] = -10000;
      rk_proj_hbd1_x[i] = -10000.;
      rk_proj_hbd1_y[i] = -10000.;
      rk_proj_hbd2_mid[i] = -10000;
      rk_proj_hbd2_x[i] = -10000.;
      rk_proj_hbd2_y[i] = -10000.;
      rk_proj_hbd3_mid[i] = -10000;
      rk_proj_hbd3_x[i] = -10000.;
      rk_proj_hbd3_y[i] = -10000.;
      auto n_hbd_proj = proj_hbd_clusters.size();
      if (n_hbd_proj >= 1) {
        auto& hbdclst = proj_hbd_clusters[0];
        rk_proj_hbd0_mid[i] = hbdclst->ModuleId();
        auto proj_hbdlpos = hbdclst->LocalPos();
        rk_proj_hbd0_x[i] = proj_hbdlpos.X();
        rk_proj_hbd0_y[i] = proj_hbdlpos.Y();
      }
      if (n_hbd_proj >= 2) {
        auto& hbdclst = proj_hbd_clusters[1];
        rk_proj_hbd1_mid[i] = hbdclst->ModuleId();
        auto proj_hbdlpos = hbdclst->LocalPos();
        rk_proj_hbd1_x[i] = proj_hbdlpos.X();
        rk_proj_hbd1_y[i] = proj_hbdlpos.Y();
      }
      if (n_hbd_proj >= 3) {
        auto& hbdclst = proj_hbd_clusters[0];
        rk_proj_hbd2_mid[i] = hbdclst->ModuleId();
        auto proj_hbdlpos = hbdclst->LocalPos();
        rk_proj_hbd2_x[i] = proj_hbdlpos.X();
        rk_proj_hbd2_y[i] = proj_hbdlpos.Y();
      }
      if (n_hbd_proj >= 4) {
        auto& hbdclst = proj_hbd_clusters[0];
        rk_proj_hbd3_mid[i] = hbdclst->ModuleId();
        auto proj_hbdlpos = hbdclst->LocalPos();
        rk_proj_hbd3_x[i] = proj_hbdlpos.X();
        rk_proj_hbd3_y[i] = proj_hbdlpos.Y();
      }
      auto& proj_lg_hits = cand.ProjectedLGHits();
      rk_proj_lg0_mid[i] = -10000;
      rk_proj_lg0_x[i] = -10000.;
      rk_proj_lg0_y[i] = -10000.;
      rk_proj_lg1_mid[i] = -10000;
      rk_proj_lg1_x[i] = -10000.;
      rk_proj_lg1_y[i] = -10000.;
      rk_proj_lg2_mid[i] = -10000;
      rk_proj_lg2_x[i] = -10000.;
      rk_proj_lg2_y[i] = -10000.;
      rk_proj_lg3_mid[i] = -10000;
      rk_proj_lg3_x[i] = -10000.;
      rk_proj_lg3_y[i] = -10000.;
      auto n_lg_proj = proj_lg_hits.size();
      if (n_lg_proj >= 1) {
        auto& lghit = proj_lg_hits[0];
        rk_proj_lg0_mid[i] = lghit->ModuleId();
        auto lglpos = lghit->LocalPos(geometry);
        rk_proj_lg0_x[i] = lglpos.X();
        rk_proj_lg0_y[i] = lglpos.Y();
      }
      if (n_lg_proj >= 2) {
        auto& lghit = proj_lg_hits[1];
        rk_proj_lg1_mid[i] = lghit->ModuleId();
        auto lglpos = lghit->LocalPos(geometry);
        rk_proj_lg1_x[i] = lglpos.X();
        rk_proj_lg1_y[i] = lglpos.Y();
      }
      if (n_lg_proj >= 3) {
        auto& lghit = proj_lg_hits[0];
        rk_proj_lg2_mid[i] = lghit->ModuleId();
        auto lglpos = lghit->LocalPos(geometry);
        rk_proj_lg2_x[i] = lglpos.X();
        rk_proj_lg2_y[i] = lglpos.Y();
      }
      if (n_lg_proj >= 4) {
        auto& lghit = proj_lg_hits[0];
        rk_proj_lg3_mid[i] = lghit->ModuleId();
        auto lglpos = lghit->LocalPos(geometry);
        rk_proj_lg3_x[i] = lglpos.X();
        rk_proj_lg3_y[i] = lglpos.Y();
      }
    }
    for (int i = 0; i < n_pairs; ++i) {
      auto& pair_vtx = cands.SelectedTrackCandidatePair(i)->vtx;
      rk_vtx_gx[i] = pair_vtx.X();
      rk_vtx_gy[i] = pair_vtx.Y();
      rk_vtx_gz[i] = pair_vtx.Z();
    }
  }
  TFile file;
  TTree* t_param;
  TTree* tree;
  // Parameter
  TVector3 sigma;
  TVector3 init_pos_error;
  int tracking_max_steps;
  int projection_max_steps;
  int gtr_time_difference_threshold[3];
  double x_sigma[5];
  double y_sigma[3];
  int min_hits_in_x_cluster;
  double gtr_y_diff_threshold;
  double gtr_peak_sum_threshold_x[3];
  double gtr_peak_sum_threshold_y;
  double raugh_fit_chi_square_threshold[2];
  double raugh_x_fit_coefficient_threhold[3];
  double raugh_y_fit_coefficient_threhold[2];
  double hbd_projection_threshold;
  double lg_projection_threshold;
  double vtx_square_threshold;
  double step_track_step_size_cm;
  int step_track_array_size;
  // Common
  int event_id;
  // Hit, Cluster
  int n_ssd_clusters;
  std::vector<int> ssd_cluster_mid;
  std::vector<double> ssd_cluster_x;
  std::vector<double> ssd_cluster_gx;
  std::vector<double> ssd_cluster_gz;
  int n_gtr100x_clusters;
  std::vector<int> gtr100x_cluster_mid;
  std::vector<double> gtr100x_cluster_x;
  std::vector<double> gtr100x_cluster_gx;
  std::vector<double> gtr100x_cluster_gz;
  int n_gtr200x_clusters;
  std::vector<int> gtr200x_cluster_mid;
  std::vector<double> gtr200x_cluster_x;
  std::vector<double> gtr200x_cluster_gx;
  std::vector<double> gtr200x_cluster_gz;
  int n_gtr300x_clusters;
  std::vector<int> gtr300x_cluster_mid;
  std::vector<double> gtr300x_cluster_x;
  std::vector<double> gtr300x_cluster_gx;
  std::vector<double> gtr300x_cluster_gz;
  int n_gtr100y_clusters;
  std::vector<int> gtr100y_cluster_mid;
  std::vector<double> gtr100x_cluster_y;
  std::vector<double> gtr100y_cluster_gy;
  std::vector<double> gtr100y_cluster_gr;
  int n_gtr100yb_clusters;
  std::vector<int> gtr100yb_cluster_mid;
  std::vector<double> gtr100yb_cluster_x;
  std::vector<double> gtr100yb_cluster_gy;
  std::vector<double> gtr100yb_cluster_gr;
  int n_gtr200y_clusters;
  std::vector<int> gtr200y_cluster_mid;
  std::vector<double> gtr200x_cluster_y;
  std::vector<double> gtr200y_cluster_gy;
  std::vector<double> gtr200y_cluster_gr;
  int n_gtr300y_clusters;
  std::vector<int> gtr300y_cluster_mid;
  std::vector<double> gtr300x_cluster_y;
  std::vector<double> gtr300y_cluster_gy;
  std::vector<double> gtr300y_cluster_gr;
  int n_hbd_clusters;
  std::vector<int> hbd_cluster_mid;
  std::vector<double> hbd_cluster_x;
  std::vector<double> hbd_cluster_y;
  std::vector<double> hbd_cluster_gx;
  std::vector<double> hbd_cluster_gy;
  std::vector<double> hbd_cluster_gz;
  int n_lg_hits;
  std::vector<int> lg_hit_mid;
  std::vector<double> lg_hit_x;
  std::vector<double> lg_hit_y;
  std::vector<double> lg_hit_gx;
  std::vector<double> lg_hit_gy;
  std::vector<double> lg_hit_gz;
  std::vector<float> lg_hit_time;
  // Track
  int n_x_cands;
  int n_y_cands;
  int n_cands;
  int n_selected;
  int n_pairs;
  std::vector<bool> is_selected;
  std::vector<double> x_raugh_fit_chi_square;
  std::vector<double> x_raugh_fit_coef0;
  std::vector<double> x_raugh_fit_coef1;
  std::vector<double> x_raugh_fit_coef2;
  std::vector<double> y_raugh_fit_chi_square;
  std::vector<double> y_raugh_fit_coef0;
  std::vector<double> y_raugh_fit_coef1;
  std::vector<double> chi_square;
  std::vector<int> n_steps;
  std::vector<int> n_calls;
  std::vector<double> rk_hit_init_mom_gx;
  std::vector<double> rk_hit_init_mom_gy;
  std::vector<double> rk_hit_init_mom_gz;
  std::vector<double> rk_hit_init_pos_gx;
  std::vector<double> rk_hit_init_pos_gy;
  std::vector<double> rk_hit_init_pos_gz;
  std::vector<double> rk_hit_ssd_gx;
  std::vector<double> rk_hit_ssd_gy;
  std::vector<double> rk_hit_ssd_gz;
  std::vector<double> rk_hit_gtr100_gx;
  std::vector<double> rk_hit_gtr100_gy;
  std::vector<double> rk_hit_gtr100_gz;
  std::vector<double> rk_hit_gtr200_gx;
  std::vector<double> rk_hit_gtr200_gy;
  std::vector<double> rk_hit_gtr200_gz;
  std::vector<double> rk_hit_gtr300_gx;
  std::vector<double> rk_hit_gtr300_gy;
  std::vector<double> rk_hit_gtr300_gz;
  std::vector<double> rk_fit_init_mom_gx;
  std::vector<double> rk_fit_init_mom_gy;
  std::vector<double> rk_fit_init_mom_gz;
  std::vector<double> rk_fit_init_pos_gx;
  std::vector<double> rk_fit_init_pos_gy;
  std::vector<double> rk_fit_init_pos_gz;
  std::vector<int> rk_fit_ssd_mid;
  std::vector<double> rk_fit_ssd_gx;
  std::vector<double> rk_fit_ssd_gy;
  std::vector<double> rk_fit_ssd_gz;
  std::vector<int> rk_fit_gtr100_mid;
  std::vector<double> rk_fit_gtr100_gx;
  std::vector<double> rk_fit_gtr100_gy;
  std::vector<double> rk_fit_gtr100_gz;
  std::vector<int> rk_fit_gtr200_mid;
  std::vector<double> rk_fit_gtr200_gx;
  std::vector<double> rk_fit_gtr200_gy;
  std::vector<double> rk_fit_gtr200_gz;
  std::vector<int> rk_fit_gtr300_mid;
  std::vector<double> rk_fit_gtr300_gx;
  std::vector<double> rk_fit_gtr300_gy;
  std::vector<double> rk_fit_gtr300_gz;
  std::vector<int> rk_fit_hbd_mid;
  std::vector<double> rk_fit_hbd_x;
  std::vector<double> rk_fit_hbd_y;
  std::vector<double> rk_fit_hbd_gx;
  std::vector<double> rk_fit_hbd_gy;
  std::vector<double> rk_fit_hbd_gz;
  std::vector<int> rk_fit_lg_c_mid;
  std::vector<double> rk_fit_lg_c_x;
  std::vector<double> rk_fit_lg_c_y;
  std::vector<double> rk_fit_lg_c_gx;
  std::vector<double> rk_fit_lg_c_gy;
  std::vector<double> rk_fit_lg_c_gz;
  std::vector<int> rk_fit_lg_b_mid;
  std::vector<double> rk_fit_lg_b_x;
  std::vector<double> rk_fit_lg_b_y;
  std::vector<double> rk_fit_lg_b_gx;
  std::vector<double> rk_fit_lg_b_gy;
  std::vector<double> rk_fit_lg_b_gz;
  std::vector<int> rk_fit_lg_a_mid;
  std::vector<double> rk_fit_lg_a_x;
  std::vector<double> rk_fit_lg_a_y;
  std::vector<double> rk_fit_lg_a_gx;
  std::vector<double> rk_fit_lg_a_gy;
  std::vector<double> rk_fit_lg_a_gz;
  std::vector<double> rk_res_ssd_x;
  std::vector<double> rk_res_gtr100_x;
  std::vector<double> rk_res_gtr100_y;
  std::vector<double> rk_res_gtr200_x;
  std::vector<double> rk_res_gtr200_y;
  std::vector<double> rk_res_gtr300_x;
  std::vector<double> rk_res_gtr300_y;
  std::vector<double> rk_proj_tgt0_gx;
  std::vector<double> rk_proj_tgt0_gy;
  std::vector<double> rk_proj_tgt0_gz;
  std::vector<double> rk_proj_tgt1_gx;
  std::vector<double> rk_proj_tgt1_gy;
  std::vector<double> rk_proj_tgt1_gz;
  std::vector<double> rk_proj_tgt2_gx;
  std::vector<double> rk_proj_tgt2_gy;
  std::vector<double> rk_proj_tgt2_gz;
  std::vector<double> rk_proj_tgt_mom0_gx;
  std::vector<double> rk_proj_tgt_mom0_gy;
  std::vector<double> rk_proj_tgt_mom0_gz;
  std::vector<double> rk_proj_tgt_mom1_gx;
  std::vector<double> rk_proj_tgt_mom1_gy;
  std::vector<double> rk_proj_tgt_mom1_gz;
  std::vector<double> rk_proj_tgt_mom2_gx;
  std::vector<double> rk_proj_tgt_mom2_gy;
  std::vector<double> rk_proj_tgt_mom2_gz;
  std::vector<int> rk_proj_hbd0_mid;
  std::vector<double> rk_proj_hbd0_x;
  std::vector<double> rk_proj_hbd0_y;
  std::vector<int> rk_proj_hbd1_mid;
  std::vector<double> rk_proj_hbd1_x;
  std::vector<double> rk_proj_hbd1_y;
  std::vector<int> rk_proj_hbd2_mid;
  std::vector<double> rk_proj_hbd2_x;
  std::vector<double> rk_proj_hbd2_y;
  std::vector<int> rk_proj_hbd3_mid;
  std::vector<double> rk_proj_hbd3_x;
  std::vector<double> rk_proj_hbd3_y;
  std::vector<int> rk_proj_lg0_mid;
  std::vector<double> rk_proj_lg0_x;
  std::vector<double> rk_proj_lg0_y;
  std::vector<int> rk_proj_lg1_mid;
  std::vector<double> rk_proj_lg1_x;
  std::vector<double> rk_proj_lg1_y;
  std::vector<int> rk_proj_lg2_mid;
  std::vector<double> rk_proj_lg2_x;
  std::vector<double> rk_proj_lg2_y;
  std::vector<int> rk_proj_lg3_mid;
  std::vector<double> rk_proj_lg3_x;
  std::vector<double> rk_proj_lg3_y;
//  std::vector<double> rk_pair_minus_gx;
//  std::vector<double> rk_pair_minus_gy;
//  std::vector<double> rk_pair_minus_gz;
  std::vector<double> rk_vtx_gx;
  std::vector<double> rk_vtx_gy;
  std::vector<double> rk_vtx_gz;
};

#endif // E16ANA_TRACKCHECKFILE_HH
