#ifndef E16ANA_TRACKCHECKFILE_HH
#define E16ANA_TRACKCHECKFILE_HH

#include <array>
#include <iostream>
#include <vector>

#include "TVector3.h"
#include "E16ANA_TrackCandidate.hh"

#include "TFile.h"
#include "TGraph.h"
#include "TH1.h"
#include "TTree.h"

class E16ANA_TrackCheckFile {
 public:
  E16ANA_TrackCheckFile(char* file_name = "tmp.root")
      : file(TFile(file_name, "recreate")) {
    tree = new TTree("tree", "tree");
    // Hit, Cluster
    tree->Branch("event_id", &event_id, "event_id/I");
    tree->Branch("n_ssd_clusters", &n_ssd_clusters);
    tree->Branch("ssd_cluster_mid", &ssd_cluster_mid);
    tree->Branch("ssd_cluster_x",   &ssd_cluster_x);
    tree->Branch("ssd_cluster_gx",  &ssd_cluster_gx);
    tree->Branch("ssd_cluster_gz",  &ssd_cluster_gz);
    tree->Branch("n_gtr100x_clusters", &n_gtr100x_clusters);
    tree->Branch("gtr100x_cluster_mid", &gtr100x_cluster_mid);
    tree->Branch("gtr100x_cluster_x",   &gtr100x_cluster_x);
    tree->Branch("gtr100x_cluster_gx",  &gtr100x_cluster_gx);
    tree->Branch("gtr100x_cluster_gz",  &gtr100x_cluster_gz);
    tree->Branch("n_gtr200x_clusters", &n_gtr200x_clusters);
    tree->Branch("gtr200x_cluster_mid", &gtr200x_cluster_mid);
    tree->Branch("gtr200x_cluster_x",   &gtr200x_cluster_x);
    tree->Branch("gtr200x_cluster_gx",  &gtr200x_cluster_gx);
    tree->Branch("gtr200x_cluster_gz",  &gtr200x_cluster_gz);
    tree->Branch("n_gtr300x_clusters", &n_gtr300x_clusters);
    tree->Branch("gtr300x_cluster_mid", &gtr300x_cluster_mid);
    tree->Branch("gtr300x_cluster_x",   &gtr300x_cluster_x);
    tree->Branch("gtr300x_cluster_gx",  &gtr300x_cluster_gx);
    tree->Branch("gtr300x_cluster_gz",  &gtr300x_cluster_gz);
    tree->Branch("n_gtr100y_clusters", &n_gtr100y_clusters);
    tree->Branch("gtr100y_cluster_mid", &gtr100y_cluster_mid);
    tree->Branch("gtr100x_cluster_y",   &gtr100x_cluster_y);
    tree->Branch("gtr100y_cluster_gy",  &gtr100y_cluster_gy);
    tree->Branch("gtr100y_cluster_gr",  &gtr100y_cluster_gr);
    tree->Branch("n_gtr100yb_clusters", &n_gtr100yb_clusters);
    tree->Branch("gtr100yb_cluster_mid", &gtr100yb_cluster_mid);
    tree->Branch("gtr100yb_cluster_x",   &gtr100yb_cluster_x);
    tree->Branch("gtr100yb_cluster_gy",  &gtr100yb_cluster_gy);
    tree->Branch("gtr100yb_cluster_gr",  &gtr100yb_cluster_gr);
    tree->Branch("n_gtr200y_clusters", &n_gtr200y_clusters);
    tree->Branch("gtr200y_cluster_mid", &gtr200y_cluster_mid);
    tree->Branch("gtr200x_cluster_y",   &gtr200x_cluster_y);
    tree->Branch("gtr200y_cluster_gy",  &gtr200y_cluster_gy);
    tree->Branch("gtr200y_cluster_gr",  &gtr200y_cluster_gr);
    tree->Branch("n_gtr300y_clusters", &n_gtr300y_clusters);
    tree->Branch("gtr300y_cluster_mid", &gtr300y_cluster_mid);
    tree->Branch("gtr300x_cluster_y",   &gtr300x_cluster_y);
    tree->Branch("gtr300y_cluster_gy",  &gtr300y_cluster_gy);
    tree->Branch("gtr300y_cluster_gr",  &gtr300y_cluster_gr);
    tree->Branch("n_hbd_clusters", &n_hbd_clusters);
    tree->Branch("hbd_cluster_mid", &hbd_cluster_mid);
    tree->Branch("hbd_cluster_x",   &hbd_cluster_x);
    tree->Branch("hbd_cluster_y",   &hbd_cluster_y);
    tree->Branch("hbd_cluster_gx",  &hbd_cluster_gx);
    tree->Branch("hbd_cluster_gy",  &hbd_cluster_gy);
    tree->Branch("hbd_cluster_gz",  &hbd_cluster_gz);
    tree->Branch("n_lg_hits", &n_lg_hits);
    tree->Branch("lg_hit_mid",  &lg_hit_mid);
    tree->Branch("lg_hit_x",    &lg_hit_x);
    tree->Branch("lg_hit_y",    &lg_hit_y);
    tree->Branch("lg_hit_gx",   &lg_hit_gx);
    tree->Branch("lg_hit_gy",   &lg_hit_gy);
    tree->Branch("lg_hit_gz",   &lg_hit_gz);
    tree->Branch("lg_hit_time", &lg_hit_time);
    // Track
    tree->Branch("n_cands", &n_cands, "n_cands/I");
    tree->Branch("n_selected", &n_selected, "n_selected/I");
    tree->Branch("is_selected", &is_selected);
    tree->Branch("chi_square", &chi_square);
    tree->Branch("n_steps", &n_steps);
    tree->Branch("n_calls", &n_calls);
    tree->Branch("rk_hit_mom_gx", &rk_hit_mom_gx);
    tree->Branch("rk_hit_mom_gy", &rk_hit_mom_gy);
    tree->Branch("rk_hit_mom_gz", &rk_hit_mom_gz);
    tree->Branch("rk_hit_tgt_gx", &rk_hit_tgt_gx);
    tree->Branch("rk_hit_tgt_gy", &rk_hit_tgt_gy);
    tree->Branch("rk_hit_tgt_gz", &rk_hit_tgt_gz);
    tree->Branch("rk_hit_ssd_gx", &rk_hit_ssd_gx);
    tree->Branch("rk_hit_ssd_gy", &rk_hit_ssd_gy);
    tree->Branch("rk_hit_ssd_gz", &rk_hit_ssd_gz);
    tree->Branch("rk_hit_gtr100_gx", &rk_hit_gtr100_gx);
    tree->Branch("rk_hit_gtr100_gy", &rk_hit_gtr100_gy);
    tree->Branch("rk_hit_gtr100_gz", &rk_hit_gtr100_gz);
    tree->Branch("rk_hit_gtr200_gx", &rk_hit_gtr200_gx);
    tree->Branch("rk_hit_gtr200_gy", &rk_hit_gtr200_gy);
    tree->Branch("rk_hit_gtr200_gz", &rk_hit_gtr200_gz);
    tree->Branch("rk_hit_gtr300_gx", &rk_hit_gtr300_gx);
    tree->Branch("rk_hit_gtr300_gy", &rk_hit_gtr300_gy);
    tree->Branch("rk_hit_gtr300_gz", &rk_hit_gtr300_gz);
    tree->Branch("rk_fit_mom_gx", &rk_fit_mom_gx);
    tree->Branch("rk_fit_mom_gy", &rk_fit_mom_gy);
    tree->Branch("rk_fit_mom_gz", &rk_fit_mom_gz);
    tree->Branch("rk_fit_tgt_gx", &rk_fit_tgt_gx);
    tree->Branch("rk_fit_tgt_gy", &rk_fit_tgt_gy);
    tree->Branch("rk_fit_tgt_gz", &rk_fit_tgt_gz);
    tree->Branch("rk_fit_ssd_mid", &rk_fit_ssd_mid);
    tree->Branch("rk_fit_ssd_gx",  &rk_fit_ssd_gx);
    tree->Branch("rk_fit_ssd_gy",  &rk_fit_ssd_gy);
    tree->Branch("rk_fit_ssd_gz",  &rk_fit_ssd_gz);
    tree->Branch("rk_fit_gtr100_mid", &rk_fit_gtr100_mid);
    tree->Branch("rk_fit_gtr100_gx",  &rk_fit_gtr100_gx);
    tree->Branch("rk_fit_gtr100_gy",  &rk_fit_gtr100_gy);
    tree->Branch("rk_fit_gtr100_gz",  &rk_fit_gtr100_gz);
    tree->Branch("rk_fit_gtr200_mid", &rk_fit_gtr200_mid);
    tree->Branch("rk_fit_gtr200_gx",  &rk_fit_gtr200_gx);
    tree->Branch("rk_fit_gtr200_gy",  &rk_fit_gtr200_gy);
    tree->Branch("rk_fit_gtr200_gz",  &rk_fit_gtr200_gz);
    tree->Branch("rk_fit_gtr300_mid", &rk_fit_gtr300_mid);
    tree->Branch("rk_fit_gtr300_gx",  &rk_fit_gtr300_gx);
    tree->Branch("rk_fit_gtr300_gy",  &rk_fit_gtr300_gy);
    tree->Branch("rk_fit_gtr300_gz",  &rk_fit_gtr300_gz);
    tree->Branch("rk_fit_hbd_mid", &rk_fit_hbd_mid);
    tree->Branch("rk_fit_hbd_gx",  &rk_fit_hbd_gx);
    tree->Branch("rk_fit_hbd_gy",  &rk_fit_hbd_gy);
    tree->Branch("rk_fit_hbd_gz",  &rk_fit_hbd_gz);
    tree->Branch("rk_fit_lg_c_mid", &rk_fit_lg_c_mid);
    tree->Branch("rk_fit_lg_c_x",   &rk_fit_lg_c_x);
    tree->Branch("rk_fit_lg_c_y",   &rk_fit_lg_c_y);
    tree->Branch("rk_fit_lg_c_gx",  &rk_fit_lg_c_gx);
    tree->Branch("rk_fit_lg_c_gy",  &rk_fit_lg_c_gy);
    tree->Branch("rk_fit_lg_c_gz",  &rk_fit_lg_c_gz);
    tree->Branch("rk_fit_lg_b_mid", &rk_fit_lg_b_mid);
    tree->Branch("rk_fit_lg_b_x",   &rk_fit_lg_b_x);
    tree->Branch("rk_fit_lg_b_y",   &rk_fit_lg_b_y);
    tree->Branch("rk_fit_lg_b_gx",  &rk_fit_lg_b_gx);
    tree->Branch("rk_fit_lg_b_gy",  &rk_fit_lg_b_gy);
    tree->Branch("rk_fit_lg_b_gz",  &rk_fit_lg_b_gz);
    tree->Branch("rk_fit_lg_a_mid", &rk_fit_lg_a_mid);
    tree->Branch("rk_fit_lg_a_x",   &rk_fit_lg_a_x);
    tree->Branch("rk_fit_lg_a_y",   &rk_fit_lg_a_y);
    tree->Branch("rk_fit_lg_a_gx",  &rk_fit_lg_a_gx);
    tree->Branch("rk_fit_lg_a_gy",  &rk_fit_lg_a_gy);
    tree->Branch("rk_fit_lg_a_gz",  &rk_fit_lg_a_gz);
    tree->Branch("rk_res_ssd_x", &rk_res_ssd_x);
    tree->Branch("rk_res_gtr100_x", &rk_res_gtr100_x);
    tree->Branch("rk_res_gtr100_y", &rk_res_gtr100_y);
    tree->Branch("rk_res_gtr200_x", &rk_res_gtr200_x);
    tree->Branch("rk_res_gtr200_y", &rk_res_gtr200_y);
    tree->Branch("rk_res_gtr300_x", &rk_res_gtr300_x);
    tree->Branch("rk_res_gtr300_y", &rk_res_gtr300_y);
    tree->Branch("rk_proj_lg0_mid", &rk_proj_lg0_mid);
    tree->Branch("rk_proj_lg0_x",   &rk_proj_lg0_x);
    tree->Branch("rk_proj_lg0_y",   &rk_proj_lg0_y);
    tree->Branch("rk_proj_lg1_mid", &rk_proj_lg1_mid);
    tree->Branch("rk_proj_lg1_x",   &rk_proj_lg1_x);
    tree->Branch("rk_proj_lg1_y",   &rk_proj_lg1_y);
    tree->Branch("rk_proj_lg2_mid", &rk_proj_lg2_mid);
    tree->Branch("rk_proj_lg2_x",   &rk_proj_lg2_x);
    tree->Branch("rk_proj_lg2_y",   &rk_proj_lg2_y);
    tree->Branch("rk_proj_lg3_mid", &rk_proj_lg3_mid);
    tree->Branch("rk_proj_lg3_x",   &rk_proj_lg3_x);
    tree->Branch("rk_proj_lg3_y",   &rk_proj_lg3_y);
  };
  ~E16ANA_TrackCheckFile() { file.Write(); }
  void AddEntry(int _event_id, E16ANA_GeometryV2& geometry, E16DST_DST1PhysicsRecord& record, E16ANA_TrackCandidates& cands) {
    event_id = _event_id;
    AddRecord(geometry, record);
    AddCandidate(geometry, cands);
    tree->Fill();
  }
 private:
  void AddRecord(E16ANA_GeometryV2& geometry, E16DST_DST1PhysicsRecord& record) {
    n_ssd_clusters = record.SSD().NumClusters();
    ssd_cluster_mid.resize(n_ssd_clusters);
    ssd_cluster_x.resize(n_ssd_clusters);
    ssd_cluster_gx.resize(n_ssd_clusters);
    ssd_cluster_gz.resize(n_ssd_clusters);
    for (int i = 0; i < n_ssd_clusters; ++i) {
      auto& clst = record.SSD().Cluster(i);
      ssd_cluster_mid[i] = clst.ModuleId();
      ssd_cluster_x[i] = clst.LocalX();
      auto gpos = clst.GlobalPos(geometry);
      ssd_cluster_gx[i] = gpos.X();
      ssd_cluster_gz[i] = gpos.Z();
    }
    gtr100x_cluster_mid.clear();
    gtr100x_cluster_x.clear();
    gtr100x_cluster_gx.clear();
    gtr100x_cluster_gz.clear();
    gtr200x_cluster_mid.clear();
    gtr200x_cluster_x.clear();
    gtr200x_cluster_gx.clear();
    gtr200x_cluster_gz.clear();
    gtr300x_cluster_mid.clear();
    gtr300x_cluster_x.clear();
    gtr300x_cluster_gx.clear();
    gtr300x_cluster_gz.clear();
    gtr100y_cluster_mid.clear();
    gtr100x_cluster_y.clear();
    gtr100y_cluster_gy.clear();
    gtr100y_cluster_gr.clear();
    gtr100yb_cluster_mid.clear();
    gtr100yb_cluster_x.clear();
    gtr100yb_cluster_gy.clear();
    gtr100yb_cluster_gr.clear();
    gtr200y_cluster_mid.clear();
    gtr200x_cluster_y.clear();
    gtr200y_cluster_gy.clear();
    gtr200y_cluster_gr.clear();
    gtr300y_cluster_mid.clear();
    gtr300x_cluster_y.clear();
    gtr300y_cluster_gy.clear();
    gtr300y_cluster_gr.clear();
    auto n_gtr_clusters = record.GTR().NumClusters();
    for (int i = 0; i < n_gtr_clusters; ++i) {
      auto& clst = record.GTR().Cluster(i);
      auto lid = clst.LayerId();
      auto type = clst.Type();
      if (lid == 0) {
        if (type == 0) {
          gtr100x_cluster_mid.emplace_back(clst.ModuleId());
          gtr100x_cluster_x.emplace_back(clst.LocalX());
          auto gpos = clst.GlobalPos(geometry);
          gtr100x_cluster_gx.emplace_back(gpos.X());
          gtr100x_cluster_gz.emplace_back(gpos.Z());
        } else if (type == 1) {
          gtr100y_cluster_mid.emplace_back(clst.ModuleId());
          gtr100x_cluster_y.emplace_back(clst.LocalX());
          auto gpos = clst.GlobalPos(geometry);
          gtr100y_cluster_gy.emplace_back(gpos.X());
          gtr100y_cluster_gr.emplace_back(gpos.Z());
        } else {
          gtr100yb_cluster_mid.emplace_back(clst.ModuleId());
          gtr100yb_cluster_x.emplace_back(clst.LocalX());
          auto gpos = clst.GlobalPos(geometry);
          gtr100yb_cluster_gy.emplace_back(gpos.X());
          gtr100yb_cluster_gr.emplace_back(gpos.Z());
        }
      } else if (lid == 1) {
        if (type == 0) {
          gtr200x_cluster_mid.emplace_back(clst.ModuleId());
          gtr200x_cluster_x.emplace_back(clst.LocalX());
          auto gpos = clst.GlobalPos(geometry);
          gtr200x_cluster_gx.emplace_back(gpos.X());
          gtr200x_cluster_gz.emplace_back(gpos.Z());
        } else if (type == 1) {
          gtr200y_cluster_mid.emplace_back(clst.ModuleId());
          gtr200x_cluster_y.emplace_back(clst.LocalX());
          auto gpos = clst.GlobalPos(geometry);
          gtr200y_cluster_gy.emplace_back(gpos.X());
          gtr200y_cluster_gr.emplace_back(gpos.Z());
        }
      } else {
        if (type == 0) {
          gtr300x_cluster_mid.emplace_back(clst.ModuleId());
          gtr300x_cluster_x.emplace_back(clst.LocalX());
          auto gpos = clst.GlobalPos(geometry);
          gtr300x_cluster_gx.emplace_back(gpos.X());
          gtr300x_cluster_gz.emplace_back(gpos.Z());
        } else if (type == 1) {
          gtr300y_cluster_mid.emplace_back(clst.ModuleId());
          gtr300x_cluster_y.emplace_back(clst.LocalX());
          auto gpos = clst.GlobalPos(geometry);
          gtr300y_cluster_gy.emplace_back(gpos.X());
          gtr300y_cluster_gr.emplace_back(gpos.Z());
        }
      }
    }
    n_hbd_clusters = record.HBD().NumClusters();
    hbd_cluster_mid.resize(n_hbd_clusters);
    hbd_cluster_x.resize(n_hbd_clusters);
    hbd_cluster_y.resize(n_hbd_clusters);
    hbd_cluster_gx.resize(n_hbd_clusters);
    hbd_cluster_gy.resize(n_hbd_clusters);
    hbd_cluster_gz.resize(n_hbd_clusters);
    for (int i = 0; i < n_hbd_clusters; ++i) {
      auto& clst = record.HBD().Cluster(i);
      hbd_cluster_mid[i] = clst.ModuleId();
      auto lpos = clst.LocalPos();
      hbd_cluster_x[i] = lpos.X();
      hbd_cluster_y[i] = lpos.Y();
      auto gpos = clst.GlobalPos(geometry);
      hbd_cluster_gx[i] = gpos.X();
      hbd_cluster_gy[i] = gpos.Y();
      hbd_cluster_gz[i] = gpos.Z();
    }
    n_lg_hits = record.LG().NumHits();
    lg_hit_mid.resize(n_lg_hits);
    lg_hit_x.resize(n_lg_hits);
    lg_hit_y.resize(n_lg_hits);
    lg_hit_gx.resize(n_lg_hits);
    lg_hit_gy.resize(n_lg_hits);
    lg_hit_gz.resize(n_lg_hits);
    lg_hit_time.resize(n_lg_hits);
    for (int i = 0; i < n_lg_hits; ++i) {
      auto& hit = record.LG().Hit(i);
      lg_hit_mid[i] = hit.ModuleId();
      auto lpos = hit.LocalPos(geometry);
      lg_hit_x[i] = lpos.X();
      lg_hit_y[i] = lpos.Y();
      auto gpos = hit.GlobalPos(geometry);
      lg_hit_gx[i] = gpos.X();
      lg_hit_gy[i] = gpos.Y();
      lg_hit_gz[i] = gpos.Z();
      lg_hit_time[i] = hit.Timing();
    }
  }
  void AddCandidate(E16ANA_GeometryV2& geometry, E16ANA_TrackCandidates& cands) {
    n_cands = cands.NumTrackCandidates();
    n_selected = cands.NumSelectedTrackCandidates();
    is_selected.resize(n_cands);
    chi_square.resize(n_cands);
    n_steps.resize(n_cands);
    n_calls.resize(n_cands);
    rk_hit_mom_gx.resize(n_cands);
    rk_hit_mom_gy.resize(n_cands);
    rk_hit_mom_gz.resize(n_cands);
    rk_hit_tgt_gx.resize(n_cands);
    rk_hit_tgt_gy.resize(n_cands);
    rk_hit_tgt_gz.resize(n_cands);
    rk_hit_ssd_gx.resize(n_cands);
    rk_hit_ssd_gy.resize(n_cands);
    rk_hit_ssd_gz.resize(n_cands);
    rk_hit_gtr100_gx.resize(n_cands);
    rk_hit_gtr100_gy.resize(n_cands);
    rk_hit_gtr100_gz.resize(n_cands);
    rk_hit_gtr200_gx.resize(n_cands);
    rk_hit_gtr200_gy.resize(n_cands);
    rk_hit_gtr200_gz.resize(n_cands);
    rk_hit_gtr300_gx.resize(n_cands);
    rk_hit_gtr300_gy.resize(n_cands);
    rk_hit_gtr300_gz.resize(n_cands);
    rk_fit_mom_gx.resize(n_cands);
    rk_fit_mom_gy.resize(n_cands);
    rk_fit_mom_gz.resize(n_cands);
    rk_fit_tgt_gx.resize(n_cands);
    rk_fit_tgt_gy.resize(n_cands);
    rk_fit_tgt_gz.resize(n_cands);
    rk_fit_ssd_mid.resize(n_cands);
    rk_fit_ssd_gx.resize(n_cands);
    rk_fit_ssd_gy.resize(n_cands);
    rk_fit_ssd_gz.resize(n_cands);
    rk_fit_gtr100_mid.resize(n_cands);
    rk_fit_gtr100_gx.resize(n_cands);
    rk_fit_gtr100_gy.resize(n_cands);
    rk_fit_gtr100_gz.resize(n_cands);
    rk_fit_gtr200_mid.resize(n_cands);
    rk_fit_gtr200_gx.resize(n_cands);
    rk_fit_gtr200_gy.resize(n_cands);
    rk_fit_gtr200_gz.resize(n_cands);
    rk_fit_gtr300_mid.resize(n_cands);
    rk_fit_gtr300_gx.resize(n_cands);
    rk_fit_gtr300_gy.resize(n_cands);
    rk_fit_gtr300_gz.resize(n_cands);
    rk_fit_hbd_mid.resize(n_cands);
    rk_fit_hbd_gx.resize(n_cands);
    rk_fit_hbd_gy.resize(n_cands);
    rk_fit_hbd_gz.resize(n_cands);
    rk_fit_lg_c_mid.resize(n_cands);
    rk_fit_lg_c_x.resize(n_cands);
    rk_fit_lg_c_y.resize(n_cands);
    rk_fit_lg_c_gx.resize(n_cands);
    rk_fit_lg_c_gy.resize(n_cands);
    rk_fit_lg_c_gz.resize(n_cands);
    rk_fit_lg_b_mid.resize(n_cands);
    rk_fit_lg_b_x.resize(n_cands);
    rk_fit_lg_b_y.resize(n_cands);
    rk_fit_lg_b_gx.resize(n_cands);
    rk_fit_lg_b_gy.resize(n_cands);
    rk_fit_lg_b_gz.resize(n_cands);
    rk_fit_lg_a_mid.resize(n_cands);
    rk_fit_lg_a_x.resize(n_cands);
    rk_fit_lg_a_y.resize(n_cands);
    rk_fit_lg_a_gx.resize(n_cands);
    rk_fit_lg_a_gy.resize(n_cands);
    rk_fit_lg_a_gz.resize(n_cands);
    rk_res_ssd_x.resize(n_cands);
    rk_res_gtr100_x.resize(n_cands);
    rk_res_gtr100_y.resize(n_cands);
    rk_res_gtr200_x.resize(n_cands);
    rk_res_gtr200_y.resize(n_cands);
    rk_res_gtr300_x.resize(n_cands);
    rk_res_gtr300_y.resize(n_cands);
    rk_proj_lg0_mid.resize(n_cands);
    rk_proj_lg0_x.resize(n_cands);
    rk_proj_lg0_y.resize(n_cands);
    rk_proj_lg1_mid.resize(n_cands);
    rk_proj_lg1_x.resize(n_cands);
    rk_proj_lg1_y.resize(n_cands);
    rk_proj_lg2_mid.resize(n_cands);
    rk_proj_lg2_x.resize(n_cands);
    rk_proj_lg2_y.resize(n_cands);
    rk_proj_lg3_mid.resize(n_cands);
    rk_proj_lg3_x.resize(n_cands);
    rk_proj_lg3_y.resize(n_cands);
    for (int i = 0; i < n_cands; ++i) {
      auto& cand = cands.TrackCandidates()[i];
      is_selected[i] = cand.IsSelected();
      chi_square[i] = cand.ChiSquare();
      n_steps[i] = cand.NumSteps();
      n_calls[i] = cand.NumCalls();
      auto hit_mom = cand.Momentum();
      rk_hit_mom_gx[i] = hit_mom.X();
      rk_hit_mom_gy[i] = hit_mom.Y();
      rk_hit_mom_gz[i] = hit_mom.Z();
      rk_hit_tgt_gx[i] = cand.Vertex().X();
      rk_hit_tgt_gy[i] = cand.Vertex().Y();
      rk_hit_tgt_gz[i] = cand.Vertex().Z();
      auto& pairs = cand.ClusterPairs();
      auto& ssdhit_gpos = pairs[0].GlobalPos();
      rk_hit_ssd_gx[i] = ssdhit_gpos.X();
      rk_hit_ssd_gy[i] = ssdhit_gpos.Y();
      rk_hit_ssd_gz[i] = ssdhit_gpos.Z();
      auto& gtr100hit_gpos = pairs[1].GlobalPos();
      rk_hit_gtr100_gx[i] = gtr100hit_gpos.X();
      rk_hit_gtr100_gy[i] = gtr100hit_gpos.Y();
      rk_hit_gtr100_gz[i] = gtr100hit_gpos.Z();
      auto& gtr200hit_gpos = pairs[2].GlobalPos();
      rk_hit_gtr200_gx[i] = gtr200hit_gpos.X();
      rk_hit_gtr200_gy[i] = gtr200hit_gpos.Y();
      rk_hit_gtr200_gz[i] = gtr200hit_gpos.Z();
      auto& gtr300hit_gpos = pairs[3].GlobalPos();
      rk_hit_gtr300_gx[i] = gtr300hit_gpos.X();
      rk_hit_gtr300_gy[i] = gtr300hit_gpos.Y();
      rk_hit_gtr300_gz[i] = gtr300hit_gpos.Z();
      auto fit_mom = cand.FitMomentum();
      rk_fit_mom_gx[i] = fit_mom.X();
      rk_fit_mom_gy[i] = fit_mom.Y();
      rk_fit_mom_gz[i] = fit_mom.Z();
      auto fit_vtx = cand.FitVertex();
      rk_fit_tgt_gx[i] = fit_vtx.X();
      rk_fit_tgt_gy[i] = fit_vtx.Y();
      rk_fit_tgt_gz[i] = fit_vtx.Z();
      const auto& fits = cand.LocalFitResults();
      rk_fit_ssd_mid[i] = fits[0].module_id;
      auto& ssdfit_gpos = fits[0].global_pos;
      rk_fit_ssd_gx[i] = ssdfit_gpos.X();
      rk_fit_ssd_gy[i] = ssdfit_gpos.Y();
      rk_fit_ssd_gz[i] = ssdfit_gpos.Z();
      rk_res_ssd_x[i] = fits[0].residual_pos.X();
      rk_fit_gtr100_mid[i] = fits[1].module_id;
      auto& gtr100fit_gpos = fits[1].global_pos;
      rk_fit_gtr100_gx[i] = gtr100fit_gpos.X();
      rk_fit_gtr100_gy[i] = gtr100fit_gpos.Y();
      rk_fit_gtr100_gz[i] = gtr100fit_gpos.Z();
      rk_res_gtr100_x[i] = fits[1].residual_pos.X();
      rk_res_gtr100_y[i] = fits[1].residual_pos.Y();
      rk_fit_gtr200_mid[i] = fits[2].module_id;
      auto& gtr200fit_gpos = fits[2].global_pos;
      rk_fit_gtr200_gx[i] = gtr200fit_gpos.X();
      rk_fit_gtr200_gy[i] = gtr200fit_gpos.Y();
      rk_fit_gtr200_gz[i] = gtr200fit_gpos.Z();
      rk_res_gtr200_x[i] = fits[2].residual_pos.X();
      rk_res_gtr200_y[i] = fits[2].residual_pos.Y();
      rk_fit_gtr300_mid[i] = fits[3].module_id;
      auto& gtr300fit_gpos = fits[3].global_pos;
      rk_fit_gtr300_gx[i] = gtr300fit_gpos.X();
      rk_fit_gtr300_gy[i] = gtr300fit_gpos.Y();
      rk_fit_gtr300_gz[i] = gtr300fit_gpos.Z();
      rk_res_gtr300_x[i] = fits[3].residual_pos.X();
      rk_res_gtr300_y[i] = fits[3].residual_pos.Y();
      rk_fit_hbd_mid[i] = fits[4].module_id;
      auto& hbdfit_gpos = fits[4].global_pos;
      rk_fit_hbd_gx[i] = hbdfit_gpos.X();
      rk_fit_hbd_gy[i] = hbdfit_gpos.Y();
      rk_fit_hbd_gz[i] = hbdfit_gpos.Z();
      rk_fit_lg_c_mid[i] = fits[5].module_id;
      auto& lgcfit_lpos = fits[5].local_pos;
      rk_fit_lg_c_x[i] = lgcfit_lpos.X();
      rk_fit_lg_c_y[i] = lgcfit_lpos.Y();
      auto& lgcfit_gpos = fits[5].global_pos;
      rk_fit_lg_c_gx[i] = lgcfit_gpos.X();
      rk_fit_lg_c_gy[i] = lgcfit_gpos.Y();
      rk_fit_lg_c_gz[i] = lgcfit_gpos.Z();
      rk_fit_lg_b_mid[i] = fits[6].module_id;
      auto& lgbfit_lpos = fits[6].local_pos;
      rk_fit_lg_b_x[i] = lgbfit_lpos.X();
      rk_fit_lg_b_y[i] = lgbfit_lpos.Y();
      auto& lgbfit_gpos = fits[6].global_pos;
      rk_fit_lg_b_gx[i] = lgbfit_gpos.X();
      rk_fit_lg_b_gy[i] = lgbfit_gpos.Y();
      rk_fit_lg_b_gz[i] = lgbfit_gpos.Z();
      rk_fit_lg_a_mid[i] = fits[7].module_id;
      auto& lgafit_lpos = fits[7].local_pos;
      rk_fit_lg_a_x[i] = lgafit_lpos.X();
      rk_fit_lg_a_y[i] = lgafit_lpos.Y();
      auto& lgafit_gpos = fits[7].global_pos;
      rk_fit_lg_a_gx[i] = lgafit_gpos.X();
      rk_fit_lg_a_gy[i] = lgafit_gpos.Y();
      rk_fit_lg_a_gz[i] = lgafit_gpos.Z();
      auto& proj_lg_hits = cand.ProjectedLGHits();
      rk_proj_lg0_mid[i] = -10000;
      rk_proj_lg0_x[i] = -10000.;
      rk_proj_lg0_y[i] = -10000.;
      rk_proj_lg1_mid[i] = -10000;
      rk_proj_lg1_x[i] = -10000.;
      rk_proj_lg1_y[i] = -10000.;
      rk_proj_lg2_mid[i] = -10000;
      rk_proj_lg2_x[i] = -10000.;
      rk_proj_lg2_y[i] = -10000.;
      rk_proj_lg3_mid[i] = -10000;
      rk_proj_lg3_x[i] = -10000.;
      rk_proj_lg3_y[i] = -10000.;
      auto n_proj = proj_lg_hits.size();
      if (n_proj >= 1) {
        auto& lghit = proj_lg_hits[0];
        rk_proj_lg0_mid[i] = lghit->ModuleId();
        auto lglpos = lghit->LocalPos(geometry);
        rk_proj_lg0_x[i] = lglpos.X();
        rk_proj_lg0_y[i] = lglpos.Y();
      }
      if (n_proj >= 2) {
        auto& lghit = proj_lg_hits[1];
        rk_proj_lg1_mid[i] = lghit->ModuleId();
        auto lglpos = lghit->LocalPos(geometry);
        rk_proj_lg1_x[i] = lglpos.X();
        rk_proj_lg1_y[i] = lglpos.Y();
      }
      if (n_proj >= 3) {
        auto& lghit = proj_lg_hits[0];
        rk_proj_lg2_mid[i] = lghit->ModuleId();
        auto lglpos = lghit->LocalPos(geometry);
        rk_proj_lg2_x[i] = lglpos.X();
        rk_proj_lg2_y[i] = lglpos.Y();
      }
      if (n_proj >= 4) {
        auto& lghit = proj_lg_hits[0];
        rk_proj_lg3_mid[i] = lghit->ModuleId();
        auto lglpos = lghit->LocalPos(geometry);
        rk_proj_lg3_x[i] = lglpos.X();
        rk_proj_lg3_y[i] = lglpos.Y();
      }
    }
  }
  TFile file;
  TTree* tree;
  int event_id;
  // Hit, Cluster
  int n_ssd_clusters;
  std::vector<int> ssd_cluster_mid;
  std::vector<double> ssd_cluster_x;
  std::vector<double> ssd_cluster_gx;
  std::vector<double> ssd_cluster_gz;
  int n_gtr100x_clusters;
  std::vector<int> gtr100x_cluster_mid;
  std::vector<double> gtr100x_cluster_x;
  std::vector<double> gtr100x_cluster_gx;
  std::vector<double> gtr100x_cluster_gz;
  int n_gtr200x_clusters;
  std::vector<int> gtr200x_cluster_mid;
  std::vector<double> gtr200x_cluster_x;
  std::vector<double> gtr200x_cluster_gx;
  std::vector<double> gtr200x_cluster_gz;
  int n_gtr300x_clusters;
  std::vector<int> gtr300x_cluster_mid;
  std::vector<double> gtr300x_cluster_x;
  std::vector<double> gtr300x_cluster_gx;
  std::vector<double> gtr300x_cluster_gz;
  int n_gtr100y_clusters;
  std::vector<int> gtr100y_cluster_mid;
  std::vector<double> gtr100x_cluster_y;
  std::vector<double> gtr100y_cluster_gy;
  std::vector<double> gtr100y_cluster_gr;
  int n_gtr100yb_clusters;
  std::vector<int> gtr100yb_cluster_mid;
  std::vector<double> gtr100yb_cluster_x;
  std::vector<double> gtr100yb_cluster_gy;
  std::vector<double> gtr100yb_cluster_gr;
  int n_gtr200y_clusters;
  std::vector<int> gtr200y_cluster_mid;
  std::vector<double> gtr200x_cluster_y;
  std::vector<double> gtr200y_cluster_gy;
  std::vector<double> gtr200y_cluster_gr;
  int n_gtr300y_clusters;
  std::vector<int> gtr300y_cluster_mid;
  std::vector<double> gtr300x_cluster_y;
  std::vector<double> gtr300y_cluster_gy;
  std::vector<double> gtr300y_cluster_gr;
  int n_hbd_clusters;
  std::vector<int> hbd_cluster_mid;
  std::vector<double> hbd_cluster_x;
  std::vector<double> hbd_cluster_y;
  std::vector<double> hbd_cluster_gx;
  std::vector<double> hbd_cluster_gy;
  std::vector<double> hbd_cluster_gz;
  int n_lg_hits;
  std::vector<int> lg_hit_mid;
  std::vector<double> lg_hit_x;
  std::vector<double> lg_hit_y;
  std::vector<double> lg_hit_gx;
  std::vector<double> lg_hit_gy;
  std::vector<double> lg_hit_gz;
  std::vector<float> lg_hit_time;
  // Track
  int n_cands;
  int n_selected;
  std::vector<bool> is_selected;
  std::vector<double> chi_square;
  std::vector<int> n_steps;
  std::vector<int> n_calls;
  std::vector<double> rk_hit_mom_gx;
  std::vector<double> rk_hit_mom_gy;
  std::vector<double> rk_hit_mom_gz;
  std::vector<double> rk_hit_tgt_gx;
  std::vector<double> rk_hit_tgt_gy;
  std::vector<double> rk_hit_tgt_gz;
  std::vector<double> rk_hit_ssd_gx;
  std::vector<double> rk_hit_ssd_gy;
  std::vector<double> rk_hit_ssd_gz;
  std::vector<double> rk_hit_gtr100_gx;
  std::vector<double> rk_hit_gtr100_gy;
  std::vector<double> rk_hit_gtr100_gz;
  std::vector<double> rk_hit_gtr200_gx;
  std::vector<double> rk_hit_gtr200_gy;
  std::vector<double> rk_hit_gtr200_gz;
  std::vector<double> rk_hit_gtr300_gx;
  std::vector<double> rk_hit_gtr300_gy;
  std::vector<double> rk_hit_gtr300_gz;
  std::vector<double> rk_fit_mom_gx;
  std::vector<double> rk_fit_mom_gy;
  std::vector<double> rk_fit_mom_gz;
  std::vector<double> rk_fit_tgt_gx;
  std::vector<double> rk_fit_tgt_gy;
  std::vector<double> rk_fit_tgt_gz;
  std::vector<double> rk_fit_ssd_mid;
  std::vector<double> rk_fit_ssd_gx;
  std::vector<double> rk_fit_ssd_gy;
  std::vector<double> rk_fit_ssd_gz;
  std::vector<double> rk_fit_gtr100_mid;
  std::vector<double> rk_fit_gtr100_gx;
  std::vector<double> rk_fit_gtr100_gy;
  std::vector<double> rk_fit_gtr100_gz;
  std::vector<double> rk_fit_gtr200_mid;
  std::vector<double> rk_fit_gtr200_gx;
  std::vector<double> rk_fit_gtr200_gy;
  std::vector<double> rk_fit_gtr200_gz;
  std::vector<double> rk_fit_gtr300_mid;
  std::vector<double> rk_fit_gtr300_gx;
  std::vector<double> rk_fit_gtr300_gy;
  std::vector<double> rk_fit_gtr300_gz;
  std::vector<double> rk_fit_hbd_mid;
  std::vector<double> rk_fit_hbd_gx;
  std::vector<double> rk_fit_hbd_gy;
  std::vector<double> rk_fit_hbd_gz;
  std::vector<double> rk_fit_lg_c_mid;
  std::vector<double> rk_fit_lg_c_x;
  std::vector<double> rk_fit_lg_c_y;
  std::vector<double> rk_fit_lg_c_gx;
  std::vector<double> rk_fit_lg_c_gy;
  std::vector<double> rk_fit_lg_c_gz;
  std::vector<double> rk_fit_lg_b_mid;
  std::vector<double> rk_fit_lg_b_x;
  std::vector<double> rk_fit_lg_b_y;
  std::vector<double> rk_fit_lg_b_gx;
  std::vector<double> rk_fit_lg_b_gy;
  std::vector<double> rk_fit_lg_b_gz;
  std::vector<double> rk_fit_lg_a_mid;
  std::vector<double> rk_fit_lg_a_x;
  std::vector<double> rk_fit_lg_a_y;
  std::vector<double> rk_fit_lg_a_gx;
  std::vector<double> rk_fit_lg_a_gy;
  std::vector<double> rk_fit_lg_a_gz;
  std::vector<double> rk_res_ssd_x;
  std::vector<double> rk_res_gtr100_x;
  std::vector<double> rk_res_gtr100_y;
  std::vector<double> rk_res_gtr200_x;
  std::vector<double> rk_res_gtr200_y;
  std::vector<double> rk_res_gtr300_x;
  std::vector<double> rk_res_gtr300_y;
  std::vector<double> rk_proj_lg0_mid;
  std::vector<double> rk_proj_lg0_x;
  std::vector<double> rk_proj_lg0_y;
  std::vector<double> rk_proj_lg1_mid;
  std::vector<double> rk_proj_lg1_x;
  std::vector<double> rk_proj_lg1_y;
  std::vector<double> rk_proj_lg2_mid;
  std::vector<double> rk_proj_lg2_x;
  std::vector<double> rk_proj_lg2_y;
  std::vector<double> rk_proj_lg3_mid;
  std::vector<double> rk_proj_lg3_x;
  std::vector<double> rk_proj_lg3_y;
};

#endif // E16ANA_TRACKCHECKFILE_HH
